### ISSUE TITLE
Maps+ stalls/hung-up when enabling Playback

### ISSUE THREAD

**Issue by PMJeffery** [sghaskell/maps-plus#40]
When enabling the Playback function, the loading animation spins forever and never recovers. 

Sample SPL:

```
index=crimes
| reverse
| eval description = "_time, crime_type", tooltip = description
| table _time, latitude, longitude, description, tooltip
```

I can enable the pathlines and it works, but enabling playback shows "Dec. 31, 1969" in the bottom left.  

I got this to work with GPS data from Waze indexed into Splunk, but similar SPL and same format settings causes the hang-up.

**Comment by PMJeffery** [comment]
You can find me internally at Splunk, mjeffery

**Comment by sghaskell** [comment]
These settings are not documented very well right now. I'll work to fix that. The problem here was that the fidelity of the points to plot was quite low and spread out over a large period of time. In order to animate properly, I set the **Tick Length** to 1 hour in milliseconds and bumped the playback speed up. This results in a quicker, choppy animation. It plays back like chess pieces moving.

For smoother playback, ensure the data set has higher fidelity over the time range. The default settings work well for most use cases with gps telemetry taken at smaller regular intervals.
