### ISSUE TITLE
Icons appears and dissapears with slow searches

### ISSUE THREAD

**Issue by SplunkUserDaniel** [sghaskell/maps-plus#5]
Hi, 
I love these maps, are the best maps that I found for splunk, but I have the next issue:

When I load the maps with a "slow" search (a search that spent between 10 seconds and 2 minutes)
The "circles" with the number in every location, appears and dissapears any times, and sometimes when the load has finished the icons are showed and other times them are not showed (when I click in the "pencil" options in design in splunk, every time I change an option icons appears and dissapear, one change appears , two changes dissapear, three appears....)

Do you have any idea how can I solve that issue?
I use splunk 6.6.4, and google chrome

Thanks a lot¡¡
Best regards

**Comment by sghaskell** [comment]
Hi @SplunkUserDaniel 

This happens due to the underlying pagination logic. The Custom Visualization API does not return the number of results that the search generates, so I have no clue when I'm done processing the results. I should technically wait until the search is done before I render any results on the map, but I cheat a beat. As a result, sometimes the map gets cleared out and everything is re-rendered. Do you eventually get all the markers you're expecting once the search finishes?

**Comment by SplunkUserDaniel** [comment]
Hi @sghaskell, thanks for your time,
The issue happens when the maps loads, appear the numbers (query running), then dissapear the numbers (query still running) then appear, then dissapear ...(and sometimes once the searches finishes are showed and other times not). When not are showed, If I click in edit and change any property the numbers appears, change another, number dissapear.
If with this explanation It is not clear, maybe I can attach a video record with my mobile
Thanks a lot¡¡
Regards
Daniel

**Comment by sghaskell** [comment]
Hi @SplunkUserDaniel - I'd update to Splunk 7.x if possible and this behavior should go away.
